#
# src/kernel/Makefile
#

include src/kernel/arch/$(ARCHT)/Makefile
include src/kernel/dev/Makefile
include src/kernel/fs/Makefile
include src/kernel/lib/Makefile
include src/kernel/mm/Makefile
include src/kernel/init/Makefile

kernel-i += -I src/kernel/dev
kernel-i += -I src/kernel/include
kernel-i += -I src/kernel/lib
