#
# src/kernel/dev/block/Makefile
#

kernel-$(CONFIG_ATA) += src/kernel/dev/block/ata.o
kernel-$(CONFIG_ATAPI) += src/kernel/dev/block/atapi.o
kernel-$(CONFIG_BLOCK) += src/kernel/dev/block/buf.o
kernel-$(CONFIG_IDE) += src/kernel/dev/block/ide.o
