#
# src/kernel/dev/char/Makefile
#

kernel-$(CONFIG_CMOS) += src/kernel/dev/char/cmos.o
kernel-$(CONFIG_PCSPK) += src/kernel/dev/char/pcspk.o
kernel-$(CONFIG_PS2KBD) += src/kernel/dev/char/ps2kbd.o
kernel-$(CONFIG_PTY) += src/kernel/dev/char/pty.o
kernel-$(CONFIG_SERIAL) += src/kernel/dev/char/serial.o
kernel-$(CONFIG_TTY) += src/kernel/dev/char/tty.o

#kernel-o += src/kernel/dev/char/null.o \
#	    src/kernel/dev/char/random.o \
#	    src/kernel/dev/char/zero.o
