#
# src/kernel/dev/char/Makefile
#

include src/kernel/dev/char/serial/Makefile

kernel-o += src/kernel/dev/char/cmos.o \
	    src/kernel/dev/char/ps2kbd.o

#kernel-o += src/kernel/dev/char/null.o \
#	    src/kernel/dev/char/random.o \
#	    src/kernel/dev/char/zero.o
