#
# src/kernel/dev/Makefile
#

#include src/kernel/dev/acpi/Makefile
include src/kernel/dev/block/Makefile
include src/kernel/dev/char/Makefile
include src/kernel/dev/pci/Makefile
include src/kernel/dev/sound/Makefile
include src/kernel/dev/timer/Makefile
include src/kernel/dev/video/Makefile

kernel-o += src/kernel/dev/dev.o
