#INC_CITO		+= ./src/cito/arch/x86_64/include
OBJS_CITO		+= ./src/cito/arch/x86_64/boot/boot.o \
				   ./src/cito/arch/x86_64/cpu/idt.o \
				   ./src/cito/arch/x86_64/cpu/int.o \
				   ./src/cito/arch/x86_64/cpu/task.o
