INC_CITO		+= ./src/cito/include
OBJS_CITO		+= ./src/cito/boot/boot.o \
				   ./src/cito/cpu/cpu.o \
				   ./src/cito/cpu/idt.o \
				   ./src/cito/cpu/int.o \
				   ./src/cito/cpu/ioapic.o \
				   ./src/cito/cpu/lapic.o \
				   ./src/cito/cpu/task.o \
				   ./src/cito/dev/cmos.o \
				   ./src/cito/dev/fb.o \
				   ./src/cito/dev/kbd.o \
				   ./src/cito/dev/pcspk.o \
				   ./src/cito/dev/pit.o \
				   ./src/cito/dev/serial.o \
				   ./src/cito/libk/stdio.o \
				   ./src/cito/libk/stdlib.o \
				   ./src/cito/libk/string.o \
				   ./src/cito/power/reboot.o \
				   ./src/cito/sys/time.o \
				   ./src/cito/main.o
