INC_CITO		+= ./src/cito/include
OBJS_CITO		+= ./src/cito/dev/cmos.o \
				   ./src/cito/dev/fb.o \
				   ./src/cito/dev/kbd.o \
				   ./src/cito/dev/pcspk.o \
				   ./src/cito/dev/pit.o \
				   ./src/cito/dev/serial.o \
				   ./src/cito/libk/stdio.o \
				   ./src/cito/libk/stdlib.o \
				   ./src/cito/libk/string.o \
				   ./src/cito/power/reboot.o \
				   ./src/cito/main.o
