#
# src/kernel/fs/Makefile
#

include src/kernel/fs/devfs/Makefile
include src/kernel/fs/iso9660/Makefile
include src/kernel/fs/memfs/Makefile

kernel-o += src/kernel/fs/dir.o \
	    src/kernel/fs/file.o \
	    src/kernel/fs/fs.o \
	    src/kernel/fs/inode.o \
	    src/kernel/fs/sb.o
