#
# src/kernel/arch/x86/Makefile
#

include src/kernel/arch/x86/boot/Makefile
include src/kernel/arch/x86/cpu/Makefile
include src/kernel/arch/x86/mm/Makefile

kernel-i += -I src/kernel/arch/x86/include
