#
# src/kernel/dev/video/Makefile
#

include src/kernel/dev/video/fonts/Makefile

kernel-$(CONFIG_CONSOLE_SERIAL) += src/kernel/dev/video/serial_con.o
kernel-$(CONFIG_CONSOLE_VGA) += src/kernel/dev/video/vga_con.o
