#
# src/kernel/dev/video/Makefile
#

include src/kernel/dev/video/fonts/Makefile

kernel-$(CONFIG_CONSOLE) += src/kernel/dev/video/console.o
kernel-$(CONFIG_VGA_CON) += src/kernel/dev/video/vga_con.o
