#
# src/kernel/dev/block/ide/Makefile
#

kernel-$(CONFIG_IDE) += src/kernel/dev/block/ide/ide.o
kernel-$(CONFIG_ATA) += src/kernel/dev/block/ide/ata.o
kernel-$(CONFIG_ATAPI) += src/kernel/dev/block/ide/atapi.o
