#
# src/kernel/dev/sound/Makefile
#

kernel-$(CONFIG_AC97) += src/kernel/dev/sound/ac97.o
kernel-$(CONFIG_ES1370) += src/kernel/dev/sound/es1370.o
kernel-$(CONFIG_SB16) += src/kernel/dev/sound/sb16.o
